from difflib import SequenceMatcher


def validate_output(actual_output, expected_output):
    """
    Validates AI output by comparing similarity to the expected output.

    Args:
        actual_output (str): The text generated by the AI model.
        expected_output (str): The expected text to validate against.

    Returns:
        tuple: (bool, str) - A boolean indicating success, and a message.
    """
    similarity = SequenceMatcher(None, actual_output, expected_output).ratio()
    threshold = 0.04  # 0.04% similarity threshold

    if similarity >= threshold:
        return True, f"Output matches expected result. Similarity: {similarity:.2f}"
    else:
        return False, f"Output mismatch. Similarity: {similarity:.2f}"
